export const certData = [
  {
    relevance: 1,
    platform: 'udacity',
    title: 'React Nanodegree',
    about: 'build web and mobile apps with react, redux, and react native',
    certificate: '2K6692SR',
  },
  {
    relevance: 1,
    platform: 'coursera',
    title: 'Responsive Web Design',
    about: '',
    certificate: '6MDY43NVV2PM',
  },
  {
    relevance: 1,
    platform: 'coursera',
    title: 'Responsive Website Basics: Code with HTML, CSS, and JavaScript',
    about: '',
    certificate: 'AGZNK75GE598',
  },
  {
    platform: 'coursera',
    relevance: 1,
    title: 'Introduction to meteor.js Development',
    about: '',
    certificate: 'V9QLMYSVNGMU',
  },
  {
    platform: 'coursera',
    relevance: 1,
    title: 'Web application development with JavaScript and MongoDB',
    about: '',
    certificate: 'TJL85PR5E5DF',
  },
  {
    platform: 'coursera',
    relevance: 1,
    title: 'Responsive website tutorials and examples',
    about: '',
    certificate: 'KMGFAXY22M4H',
  },
  {
    platform: 'coursera',
    relevance: 2,
    title: 'Introduction to Data Science in Python',
    about: '',
    certificate: 'X6A6QRBLUW2Q',
  },
  {
    platform: 'coursera',
    relevance: 2,
    title: 'Applied Plotting, Charting &amp; Data Representation in Python',
    about: '',
    certificate: 'DUWUTBMZY3SR',
  },
  {
    platform: 'coursera',
    relevance: 3,
    title: 'GIS Data Formats, Design and Quality',
    about: '',
    certificate: 'XYZS2T3AAPTR',
  },
  {
    platform: 'coursera',
    relevance: 3,
    title: 'Fundamentals of GIS',
    about: '',
    certificate: '7U44SUBPYZWG',
  },
  {
    platform: 'coursera',
    relevance: 3,
    title: 'Geospatial and Environmental Analysis',
    about: '',
    certificate: 'BECZDCJZ26SC',
  },
  {
    platform: 'coursera',
    relevance: 1,
    title: 'Successful Negotiation: Essential Strategies and Skills',
    about: '',
    certificate: 'V7MH7XK5EK7Q',
  },
  {
    platform: 'coursera',
    relevance: 4,
    title: 'Fundamentals of Project Planning and Management',
    about: '',
    certificate: 'Y5QNPW4J7KPD',
  },
  {
    platform: 'coursera',
    relevance: 4,
    title: 'Initiating and Planning Projects',
    about: '',
    certificate: 'B8HYXRYVVVB4',
  },
  {
    platform: 'coursera',
    relevance: 4,
    title: 'Construction Project Management',
    about: '',
    certificate: '2QE4KL6QT2CN',
  },
  {
    platform: 'coursera',
    relevance: 4,
    title: 'Construction Scheduling',
    about: '',
    certificate: '2JSFQKYUAFKW',
  },
  {
    platform: 'iversity',
    relevance: 4,
    title: 'Modelling and Simulation using Simulink',
    about: '',
    certificate: 'DrvhHL',
  },
];
