import { useState, useEffect } from "react";
import Head from "next/head";
import { useRouter } from "next/router";

export const PageHead = () => {
  const router = useRouter();

  const [ogUrl, setOgUrl] = useState("");
  const [ogImage, setOgImage] = useState("/pictures/pix-suit.jpg");

  let titleText = "Welcome";

  switch (router.pathname) {
    case "/portfolio":
      titleText = "My Portfolio";
      break;
    case "/publications":
      titleText = "My publications";
      break;
    case "/certifications":
      titleText = "My Certifications";
      break;
    default:
      break;
  }

  const browserTitle = `${titleText} | Orji Chidi`;
  const description = "This is the personal website of Chidi Orji.";

  useEffect(() => {
    const host = window.location.host;
    const baseUrl = `https://${host}`;

    setOgUrl(`${baseUrl}${router.pathname}`);
  }, [router.pathname]);

  return (
    <Head>
      <title>{browserTitle}</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <link
        rel="stylesheet"
        href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css"
        integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We"
        crossOrigin="anonymous"
      />

      <meta property="og:url" content={ogUrl} />
      <meta property="og:type" content="website" />
      <meta property="og:title" content={browserTitle} />
      <meta name="twitter:card" content="summary" />
      <meta property="og:description" content={description} />
      <meta property="og:image" content={ogImage} />
      <meta property="og:image:alt" content="A picture of me smiling." />
    </Head>
  );
};
