import { Certificate, LearningPlatform } from "types/index";

export const certificates: Certificate[] = [
  {
    id: "2K6692SR",
    relevance: 1,
    title: "React Nanodegree",
    platform: LearningPlatform.udacity,
    certificate_url: "https://confirm.udacity.com",
    about: "Build web and mobile apps with react, redux, and react native",
  },
  {
    id: "6MDY43NVV2PM",
    relevance: 1,
    title: "Responsive Web Design",
    platform: LearningPlatform.coursera,
    certificate_url: "https://www.coursera.org/account/accomplishments/verify",
    about: "",
  },
  {
    id: "AGZNK75GE598",
    relevance: 1,
    title: "Responsive Website Basics: Code with HTML, CSS, and JavaScript",
    platform: LearningPlatform.coursera,
    certificate_url: "https://www.coursera.org/account/accomplishments/verify",
    about: "",
  },
  {
    id: "V9QLMYSVNGMU",
    relevance: 1,
    title: "Introduction to meteor.js Development",
    platform: LearningPlatform.coursera,
    certificate_url: "https://www.coursera.org/account/accomplishments/verify",
    about: "",
  },
  {
    id: "TJL85PR5E5DF",
    relevance: 1,
    title: "Web application development with JavaScript and MongoDB",
    platform: LearningPlatform.coursera,
    certificate_url: "https://www.coursera.org/account/accomplishments/verify",
    about: "",
  },
  {
    id: "KMGFAXY22M4H",
    relevance: 1,
    title: "Responsive website tutorials and examples",
    platform: LearningPlatform.coursera,
    certificate_url: "https://www.coursera.org/account/accomplishments/verify",
    about: "",
  },
  {
    id: "X6A6QRBLUW2Q",
    relevance: 2,
    title: "Introduction to Data Science in Python",
    platform: LearningPlatform.coursera,
    certificate_url: "https://www.coursera.org/account/accomplishments/verify",
    about: "",
  },
  {
    id: "DUWUTBMZY3SR",
    relevance: 2,
    title: "Applied Plotting, Charting & Data Representation in Python",
    platform: LearningPlatform.coursera,
    certificate_url: "https://www.coursera.org/account/accomplishments/verify",
    about: "",
  },
  {
    id: "XYZS2T3AAPTR",
    relevance: 3,
    title: "GIS Data Formats, Design and Quality",
    platform: LearningPlatform.coursera,
    certificate_url: "https://www.coursera.org/account/accomplishments/verify",
    about: "",
  },
  {
    id: "7U44SUBPYZWG",
    relevance: 3,
    title: "Fundamentals of GIS",
    platform: LearningPlatform.coursera,
    certificate_url: "https://www.coursera.org/account/accomplishments/verify",
    about: "",
  },
  {
    id: "BECZDCJZ26SC",
    relevance: 3,
    title: "Geospatial and Environmental Analysis",
    platform: LearningPlatform.coursera,
    certificate_url: "https://www.coursera.org/account/accomplishments/verify",
    about: "",
  },
  {
    id: "V7MH7XK5EK7Q",
    relevance: 1,
    title: "Successful Negotiation: Essential Strategies and Skills",
    platform: LearningPlatform.coursera,
    certificate_url: "https://www.coursera.org/account/accomplishments/verify",
    about: "",
  },
  {
    id: "Y5QNPW4J7KPD",
    relevance: 4,
    title: "Fundamentals of Project Planning and Management",
    platform: LearningPlatform.coursera,
    certificate_url: "https://www.coursera.org/account/accomplishments/verify",
    about: "",
  },
  {
    id: "B8HYXRYVVVB4",
    relevance: 4,
    title: "Initiating and Planning Projects",
    platform: LearningPlatform.coursera,
    certificate_url: "https://www.coursera.org/account/accomplishments/verify",
    about: "",
  },
  {
    id: "2QE4KL6QT2CN",
    relevance: 4,
    title: "Construction Project Management",
    platform: LearningPlatform.coursera,
    certificate_url: "https://www.coursera.org/account/accomplishments/verify",
    about: "",
  },
  {
    id: "2JSFQKYUAFKW",
    relevance: 4,
    title: "Construction Scheduling",
    platform: LearningPlatform.coursera,
    certificate_url: "https://www.coursera.org/account/accomplishments/verify",
    about: "",
  },
  {
    id: "DrvhHL",
    relevance: 4,
    title: "Modelling and Simulation using Simulink",
    platform: LearningPlatform.iversity,
    certificate_url: "https://iversity.org/verify",
    about: "",
  },
];
