import { Provider } from "react-redux";
import { Footer } from "../components/Footer";
import Sidebar from "../components/Sidebar";
import { TopNavigation } from "../components/TopNavigation";
import { store } from "../store/store";
import "../styles/globals.css";
import Head from "next/head";
import Container from "react-bootstrap/Container";
import styles from "./_app.module.scss";
import { ScrollToTop } from "../components/ScrollToTop";

function MyApp({ Component, pageProps }) {
  return (
    <Provider store={store}>
      <Head>
        <title>Orji Chidi Matthew - Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css"
          integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We"
          crossOrigin="anonymous"
        />
      </Head>

      <Container
        fluid
        className={styles.top_level_container}
        style={{ padding: 0 }}
      >
        <TopNavigation />

        <Container className={styles.components_wrapper_container} style={{paddingLeft: '0'}}>
          <Component {...pageProps} />
        </Container>
        <Footer />
        <Sidebar />
        {/* <ScrollToTop /> */}
      </Container>
    </Provider>
  );
}

export default MyApp;
